# add the dlc you want to fake here
# APPID = DLC Name
# copying a file from windows creamapi will not work, you need to fix line endings
# the DLC id's below are for HOI4
[config]
# if we should also list the DLCs you own and not just the ones on this list
issubscribedapp_on_false_use_real = true

[methods]
disable_steamapps_issubscribedapp = false

[dlc]
447680 = Stellaris: Symbols of Domination
447683 = Stellaris: Arachnoid Portrait Pack
447681 = Stellaris: Sign-up Campaign Bonus
498870 = Stellaris: Plantoids Species Pack
462720 = Stellaris: Creatures of the Void
518910 = Stellaris: Leviathans Story Pack
554350 = Stellaris: Horizon Signal
553280 = Stellaris: Utopia
633310 = Stellaris: Anniversary Portraits
642750 = Stellaris: Synthetic Dawn
716670 = Stellaris: Apocalypse
756010 = Stellaris: Humanoids Species Pack
844810 = Stellaris: Distant Stars Story Pack
944290 = Stellaris: MegaCorp
1045980 = Stellaris: Ancient Relics Story Pack
1140000 = Stellaris: Lithoids Species Pack
1140001 = Stellaris: Federations
1341520 = Stellaris: Necroids Species Pack
1522090 = Stellaris: Nemesis
1749080 = Stellaris: Aquatics Species Pack
1889490 = Stellaris: Overlord
2115770 = Stellaris: Toxoids Species Pack
2277860 = Stellaris: First Contact Story Pack
2380030 = Stellaris: Galactic Paragons
2534090 = Stellaris: Astral Planes
2840100 = Stellaris: The Machine Age
2863180 = Stellaris: Rick The Cube Species Portrait