# -*- coding: utf-8 -*-

# This file is copy form en, I am not sure if it is correct

# Form implementation generated from reading ui file 'C:/Users/sp21/PycharmProjects/stellaris-dlc-unlock/design/languages/installer_zh_cn.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import design.resources_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 330)
        MainWindow.setMinimumSize(QtCore.QSize(510, 330))
        MainWindow.setMaximumSize(QtCore.QSize(510, 330))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 511, 341))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.next_button = QtWidgets.QPushButton(self.page_2)
        self.next_button.setGeometry(QtCore.QRect(350, 300, 75, 23))
        self.next_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_button.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.next_button.setObjectName("next_button")
        self.cancel_button = QtWidgets.QPushButton(self.page_2)
        self.cancel_button.setGeometry(QtCore.QRect(430, 300, 75, 23))
        self.cancel_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_button.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.cancel_button.setObjectName("cancel_button")
        self.line = QtWidgets.QFrame(self.page_2)
        self.line.setGeometry(QtCore.QRect(190, 290, 331, 1))
        self.line.setStyleSheet("border-top: 1px solid black;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hello_msg = QtWidgets.QTextBrowser(self.page_2)
        self.hello_msg.setGeometry(QtCore.QRect(210, 10, 281, 71))
        self.hello_msg.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.hello_msg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hello_msg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hello_msg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hello_msg.setObjectName("hello_msg")
        self.hello2_msg = QtWidgets.QTextBrowser(self.page_2)
        self.hello2_msg.setGeometry(QtCore.QRect(210, 120, 281, 41))
        self.hello2_msg.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.hello2_msg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hello2_msg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hello2_msg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.hello2_msg.setObjectName("hello2_msg")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page_2)
        self.textBrowser_3.setGeometry(QtCore.QRect(210, 170, 281, 41))
        self.textBrowser_3.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.listWidget_4 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_4.setGeometry(QtCore.QRect(0, 0, 191, 291))
        self.listWidget_4.setStyleSheet("background-image: url(:/images/stallaris_ba (1).jpg);")
        self.listWidget_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_4.setObjectName("listWidget_4")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.line_3 = QtWidgets.QFrame(self.page_3)
        self.line_3.setGeometry(QtCore.QRect(190, 290, 331, 1))
        self.line_3.setStyleSheet("border-top: 1px solid black;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.next_button_3 = QtWidgets.QPushButton(self.page_3)
        self.next_button_3.setEnabled(False)
        self.next_button_3.setGeometry(QtCore.QRect(350, 300, 75, 23))
        self.next_button_3.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.next_button_3.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.next_button_3.setObjectName("next_button_3")
        self.cancel_button_3 = QtWidgets.QPushButton(self.page_3)
        self.cancel_button_3.setGeometry(QtCore.QRect(430, 300, 75, 23))
        self.cancel_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_button_3.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.cancel_button_3.setObjectName("cancel_button_3")
        self.listWidget_3 = QtWidgets.QListWidget(self.page_3)
        self.listWidget_3.setGeometry(QtCore.QRect(0, 0, 191, 291))
        self.listWidget_3.setStyleSheet("background-image: url(:/images/stallaris_ba (1).jpg);")
        self.listWidget_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_3.setObjectName("listWidget_3")
        self.back_button_2 = QtWidgets.QPushButton(self.page_3)
        self.back_button_2.setGeometry(QtCore.QRect(270, 300, 75, 23))
        self.back_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_button_2.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.back_button_2.setObjectName("back_button_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser.setGeometry(QtCore.QRect(210, 10, 281, 31))
        self.textBrowser.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(210, 40, 281, 41))
        self.textBrowser_2.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.line_4 = QtWidgets.QFrame(self.page_3)
        self.line_4.setGeometry(QtCore.QRect(190, 80, 331, 1))
        self.line_4.setStyleSheet("border-top: 1px solid black;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_4.setGeometry(QtCore.QRect(210, 90, 281, 121))
        self.textBrowser_4.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_4.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.eula_true = QtWidgets.QRadioButton(self.page_3)
        self.eula_true.setGeometry(QtCore.QRect(210, 240, 231, 21))
        self.eula_true.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eula_true.setObjectName("eula_true")
        self.eula = QtWidgets.QButtonGroup(MainWindow)
        self.eula.setObjectName("eula")
        self.eula.addButton(self.eula_true)
        self.eula_false = QtWidgets.QRadioButton(self.page_3)
        self.eula_false.setGeometry(QtCore.QRect(210, 260, 231, 21))
        self.eula_false.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eula_false.setAcceptDrops(False)
        self.eula_false.setChecked(True)
        self.eula_false.setObjectName("eula_false")
        self.eula.addButton(self.eula_false)
        self.eula_true1 = QtWidgets.QRadioButton(self.page_3)
        self.eula_true1.setGeometry(QtCore.QRect(210, 220, 281, 21))
        self.eula_true1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eula_true1.setAcceptDrops(False)
        self.eula_true1.setChecked(False)
        self.eula_true1.setObjectName("eula_true1")
        self.eula.addButton(self.eula_true1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.back_button_3 = QtWidgets.QPushButton(self.page_4)
        self.back_button_3.setGeometry(QtCore.QRect(270, 300, 75, 23))
        self.back_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_button_3.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.back_button_3.setObjectName("back_button_3")
        self.line_5 = QtWidgets.QFrame(self.page_4)
        self.line_5.setGeometry(QtCore.QRect(190, 80, 331, 1))
        self.line_5.setStyleSheet("border-top: 1px solid black;")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.next_button_4 = QtWidgets.QPushButton(self.page_4)
        self.next_button_4.setGeometry(QtCore.QRect(350, 300, 75, 23))
        self.next_button_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_button_4.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.next_button_4.setObjectName("next_button_4")
        self.line_6 = QtWidgets.QFrame(self.page_4)
        self.line_6.setGeometry(QtCore.QRect(190, 290, 331, 1))
        self.line_6.setStyleSheet("border-top: 1px solid black;")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.page_4)
        self.textBrowser_5.setGeometry(QtCore.QRect(210, 90, 281, 191))
        self.textBrowser_5.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"\n"
"text-decoration: none;\n"
"")
        self.textBrowser_5.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.cancel_button_4 = QtWidgets.QPushButton(self.page_4)
        self.cancel_button_4.setGeometry(QtCore.QRect(430, 300, 75, 23))
        self.cancel_button_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_button_4.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.cancel_button_4.setObjectName("cancel_button_4")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.page_4)
        self.textBrowser_6.setGeometry(QtCore.QRect(210, 40, 281, 35))
        self.textBrowser_6.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.page_4)
        self.textBrowser_7.setGeometry(QtCore.QRect(210, 10, 281, 31))
        self.textBrowser_7.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.next_button_2 = QtWidgets.QPushButton(self.page)
        self.next_button_2.setGeometry(QtCore.QRect(350, 300, 75, 23))
        self.next_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_button_2.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.next_button_2.setObjectName("next_button_2")
        self.cancel_button_2 = QtWidgets.QPushButton(self.page)
        self.cancel_button_2.setGeometry(QtCore.QRect(430, 300, 75, 23))
        self.cancel_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_button_2.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.cancel_button_2.setObjectName("cancel_button_2")
        self.path_place = QtWidgets.QTextEdit(self.page)
        self.path_place.setGeometry(QtCore.QRect(210, 150, 281, 25))
        self.path_place.setStyleSheet("")
        self.path_place.setFrameShape(QtWidgets.QFrame.Box)
        self.path_place.setObjectName("path_place")
        self.locate_folder = QtWidgets.QPushButton(self.page)
        self.locate_folder.setGeometry(QtCore.QRect(410, 180, 75, 23))
        self.locate_folder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.locate_folder.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.locate_folder.setObjectName("locate_folder")
        self.back_button = QtWidgets.QPushButton(self.page)
        self.back_button.setGeometry(QtCore.QRect(270, 300, 75, 23))
        self.back_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_button.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setGeometry(QtCore.QRect(190, 290, 331, 1))
        self.line_2.setStyleSheet("border-top: 1px solid black;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_8.setGeometry(QtCore.QRect(210, 10, 281, 31))
        self.textBrowser_8.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.page)
        self.textBrowser_9.setGeometry(QtCore.QRect(210, 40, 281, 35))
        self.textBrowser_9.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.line_7 = QtWidgets.QFrame(self.page)
        self.line_7.setGeometry(QtCore.QRect(190, 80, 331, 1))
        self.line_7.setStyleSheet("border-top: 1px solid black;")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.space_req = QtWidgets.QLineEdit(self.page)
        self.space_req.setGeometry(QtCore.QRect(210, 250, 291, 20))
        self.space_req.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.space_req.setFrame(False)
        self.space_req.setReadOnly(True)
        self.space_req.setObjectName("space_req")
        self.stackedWidget.addWidget(self.page)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.line_8 = QtWidgets.QFrame(self.page_5)
        self.line_8.setGeometry(QtCore.QRect(190, 290, 331, 1))
        self.line_8.setStyleSheet("border-top: 1px solid black;")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.page_5)
        self.textBrowser_10.setGeometry(QtCore.QRect(210, 40, 281, 35))
        self.textBrowser_10.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.page_5)
        self.textBrowser_11.setGeometry(QtCore.QRect(210, 10, 281, 31))
        self.textBrowser_11.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.line_9 = QtWidgets.QFrame(self.page_5)
        self.line_9.setGeometry(QtCore.QRect(190, 80, 331, 1))
        self.line_9.setStyleSheet("border-top: 1px solid black;")
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.download_progressBar = QtWidgets.QProgressBar(self.page_5)
        self.download_progressBar.setGeometry(QtCore.QRect(210, 110, 281, 21))
        self.download_progressBar.setProperty("value", 0)
        self.download_progressBar.setObjectName("download_progressBar")
        self.download_text = QtWidgets.QLineEdit(self.page_5)
        self.download_text.setGeometry(QtCore.QRect(210, 140, 171, 20))
        self.download_text.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.download_text.setFrame(False)
        self.download_text.setReadOnly(True)
        self.download_text.setObjectName("download_text")
        self.next_button_5 = QtWidgets.QPushButton(self.page_5)
        self.next_button_5.setEnabled(False)
        self.next_button_5.setGeometry(QtCore.QRect(350, 300, 75, 23))
        self.next_button_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_button_5.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.next_button_5.setObjectName("next_button_5")
        self.cancel_button_5 = QtWidgets.QPushButton(self.page_5)
        self.cancel_button_5.setEnabled(False)
        self.cancel_button_5.setGeometry(QtCore.QRect(430, 300, 75, 23))
        self.cancel_button_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_button_5.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.cancel_button_5.setObjectName("cancel_button_5")
        self.label = QtWidgets.QLabel(self.page_5)
        self.label.setGeometry(QtCore.QRect(210, 86, 91, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_5)
        self.label_2.setGeometry(QtCore.QRect(210, 260, 121, 20))
        self.label_2.setObjectName("label_2")
        self.creamapi_progressBar_2 = QtWidgets.QProgressBar(self.page_5)
        self.creamapi_progressBar_2.setGeometry(QtCore.QRect(340, 260, 171, 21))
        self.creamapi_progressBar_2.setProperty("value", 0)
        self.creamapi_progressBar_2.setObjectName("creamapi_progressBar_2")
        self.speed_label = QtWidgets.QLabel(self.page_5)
        self.speed_label.setGeometry(QtCore.QRect(376, 140, 121, 20))
        self.speed_label.setObjectName("speed_label")
        self.label_3 = QtWidgets.QLabel(self.page_5)
        self.label_3.setGeometry(QtCore.QRect(210, 170, 241, 20))
        self.label_3.setObjectName("label_3")
        self.download_progressBar_2 = QtWidgets.QProgressBar(self.page_5)
        self.download_progressBar_2.setGeometry(QtCore.QRect(210, 200, 281, 21))
        self.download_progressBar_2.setProperty("value", 0)
        self.download_progressBar_2.setObjectName("download_progressBar_2")
        self.download_text_2 = QtWidgets.QLineEdit(self.page_5)
        self.download_text_2.setGeometry(QtCore.QRect(210, 230, 291, 20))
        self.download_text_2.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.download_text_2.setText("")
        self.download_text_2.setFrame(False)
        self.download_text_2.setReadOnly(True)
        self.download_text_2.setObjectName("download_text_2")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.page_6)
        self.textBrowser_12.setGeometry(QtCore.QRect(210, 10, 281, 31))
        self.textBrowser_12.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.line_11 = QtWidgets.QFrame(self.page_6)
        self.line_11.setGeometry(QtCore.QRect(190, 80, 331, 1))
        self.line_11.setStyleSheet("border-top: 1px solid black;")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.page_6)
        self.textBrowser_13.setGeometry(QtCore.QRect(210, 40, 281, 35))
        self.textBrowser_13.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.reinstall_button = QtWidgets.QPushButton(self.page_6)
        self.reinstall_button.setEnabled(True)
        self.reinstall_button.setGeometry(QtCore.QRect(350, 300, 75, 23))
        self.reinstall_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reinstall_button.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.reinstall_button.setObjectName("reinstall_button")
        self.cancel_button_6 = QtWidgets.QPushButton(self.page_6)
        self.cancel_button_6.setGeometry(QtCore.QRect(430, 300, 75, 23))
        self.cancel_button_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_button_6.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.cancel_button_6.setObjectName("cancel_button_6")
        self.reinstall_low = QtWidgets.QTextBrowser(self.page_6)
        self.reinstall_low.setGeometry(QtCore.QRect(210, 130, 281, 35))
        self.reinstall_low.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.reinstall_low.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.reinstall_low.setObjectName("reinstall_low")
        self.reinstall_up = QtWidgets.QLabel(self.page_6)
        self.reinstall_up.setGeometry(QtCore.QRect(210, 90, 281, 35))
        self.reinstall_up.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.reinstall_up.setObjectName("reinstall_up")
        self.reinstall_progress = QtWidgets.QProgressBar(self.page_6)
        self.reinstall_progress.setGeometry(QtCore.QRect(200, 160, 281, 21))
        self.reinstall_progress.setStyleSheet("")
        self.reinstall_progress.setProperty("value", 0)
        self.reinstall_progress.setTextVisible(True)
        self.reinstall_progress.setObjectName("reinstall_progress")
        self.progress_label = QtWidgets.QLabel(self.page_6)
        self.progress_label.setGeometry(QtCore.QRect(210, 140, 271, 16))
        self.progress_label.setObjectName("progress_label")
        self.now_reinstalling = QtWidgets.QLabel(self.page_6)
        self.now_reinstalling.setGeometry(QtCore.QRect(210, 190, 261, 16))
        self.now_reinstalling.setObjectName("now_reinstalling")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.finish_text = QtWidgets.QTextBrowser(self.page_7)
        self.finish_text.setGeometry(QtCore.QRect(210, 100, 281, 61))
        self.finish_text.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.finish_text.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.finish_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.finish_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.finish_text.setObjectName("finish_text")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.page_7)
        self.textBrowser_16.setGeometry(QtCore.QRect(210, 10, 281, 31))
        self.textBrowser_16.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_16.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_16.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.page_7)
        self.textBrowser_17.setGeometry(QtCore.QRect(210, 40, 281, 35))
        self.textBrowser_17.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_17.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_17.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.line_12 = QtWidgets.QFrame(self.page_7)
        self.line_12.setGeometry(QtCore.QRect(190, 80, 331, 1))
        self.line_12.setStyleSheet("border-top: 1px solid black;")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.finish_button = QtWidgets.QPushButton(self.page_7)
        self.finish_button.setEnabled(False)
        self.finish_button.setGeometry(QtCore.QRect(430, 300, 75, 23))
        self.finish_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.finish_button.setStyleSheet("QPushButton {border: 1px solid #B22222;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFD0D1;\n"
"}")
        self.finish_button.setObjectName("finish_button")
        self.launch_game = QtWidgets.QCheckBox(self.page_7)
        self.launch_game.setGeometry(QtCore.QRect(210, 200, 231, 21))
        self.launch_game.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.launch_game.setObjectName("launch_game")
        self.checkBox = QtWidgets.QCheckBox(self.page_7)
        self.checkBox.setEnabled(False)
        self.checkBox.setGeometry(QtCore.QRect(210, 250, 251, 21))
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.stackedWidget.addWidget(self.page_7)
        self.listWidget_5 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_5.setGeometry(QtCore.QRect(0, 0, 191, 291))
        self.listWidget_5.setStyleSheet("background-image: url(:/images/stallaris_ba (1).jpg);")
        self.listWidget_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_5.setObjectName("listWidget_5")
        self.version = QtWidgets.QLineEdit(self.centralwidget)
        self.version.setGeometry(QtCore.QRect(10, 300, 113, 20))
        self.version.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.version.setFrame(False)
        self.version.setReadOnly(True)
        self.version.setObjectName("version")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(190, 290, 331, 1))
        self.line_10.setStyleSheet("border-top: 1px solid black;")
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_15.setGeometry(QtCore.QRect(100, 300, 100, 20))
        self.textBrowser_15.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_15.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_15.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.dlc_list = QtWidgets.QListWidget(self.centralwidget)
        self.dlc_list.setGeometry(QtCore.QRect(510, 11, 201, 311))
        self.dlc_list.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border: 1px solid #B22222;")
        self.dlc_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dlc_list.setObjectName("dlc_list")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主窗口"))
        self.next_button.setText(_translate("MainWindow", "下一步"))
        self.cancel_button.setText(_translate("MainWindow", "取消"))
        self.hello_msg.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">欢迎使用 Stellaris DLC 解锁器 [unknown]</span><span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.hello2_msg.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">该程序将解锁 Stellaris 游戏版本 [unknown] 的所有 DLC<span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">点击 &quot;下一步 &quot; 继续或 &quot;取消&quot; 来取消安装.<span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.next_button_3.setText(_translate("MainWindow", "下一步"))
        self.cancel_button_3.setText(_translate("MainWindow", "取消"))
        self.back_button_2.setText(_translate("MainWindow", "返回"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">信息</span><span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">在继续前，请阅读以下信息。<span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 此解锁器完全免费。禁止任何形式将此解锁器用于任何商业行为。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. 本解锁器“按原样”提供，不提供任何形式的担保。使用此修改版游戏风险自负。修改者不承担因使用或误用此修改版而导致的任何损失或数据损坏，以及在使用过程中可能发生的任何利润损失。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. 未在此明确授予的所有权利均由版权持有者保留。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5. 安装并使用此修改意味着您已阅读并理解了本许可协议的条款，并同意遵守。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.eula_true.setText(_translate("MainWindow", "我接受协议条款"))
        self.eula_false.setText(_translate("MainWindow", "我不接受协议条款"))
        self.eula_true1.setText(_translate("MainWindow", "我没有阅读，但我接受其中所有内容"))
        self.back_button_3.setText(_translate("MainWindow", "返回"))
        self.next_button_4.setText(_translate("MainWindow", "下一步"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">Stellaris DLC 解锁器</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">要求</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"> </span><span style=\" font-size:9pt;\"> </span><span style=\" font-size:9pt; font-weight:600;\">Steam</span><span style=\" font-size:10pt;\">: 已购买Stellaris</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">安装</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"> </span><span style=\" font-size:9pt;\"> 按照安装程序的指示进行安装。安装过程几乎完全自动化。 </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; text-decoration: underline;\">卸载</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\"> </span><span style=\" font-size:9pt;\"> 重新安装 Paradox 启动器，删除游戏目录中的“dlc”文件夹。不要忘记重新下载您购买的 DLC。<br /><br /> 为每个人，用爱制作。<br /></span><img src=\":/images/telegram (1).png\" /><a href=\"https://t.me/seuyh\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">seuyh</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/GitHub-Logo.wine (1).png\" /><a href=\"https://github.com/yige-yigeren\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">中文翻译@武乙凌薇<br /></span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/GitHub-Logo.wine (1).png\" /><a href=\"https://github.com/seuyh/stellaris-dlc-unlocker\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">GitHub<br /></span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#000000;\">特别感谢一直以来更新手动安装解锁器的人。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/telegram (1).png\" /><a href=\"https://t.me/Temri1337\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">He11oThere</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"@Temri1337\"><span style=\" font-size:8pt; text-decoration: underline; color:#000000;\"><br /></span></a><a href=\"https://www.playground.ru/stellaris/cheat/stellaris_dlc_unlocker_razblokirovschik_dopolnenij_3_10-1088979#29894040\"><span style=\" font-size:10pt; text-decoration: underline; color:#0000ff;\">playground.ru Stellaris DLC Unlocker</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; color:#0000ff;\"><br /></p></body></html>"))
        self.cancel_button_4.setText(_translate("MainWindow", "取消"))
        self.textBrowser_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">在继续之前，请阅读以下重要信息。<span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">信息</span><span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.next_button_2.setText(_translate("MainWindow", "下一步"))
        self.cancel_button_2.setText(_translate("MainWindow", "取消"))
        self.locate_folder.setText(_translate("MainWindow", "浏览..."))
        self.back_button.setText(_translate("MainWindow", "返回"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">选择游戏文件夹</span><span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果我们无法自动找到游戏文件夹，请指定游戏文件夹。<span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.space_req.setText(_translate("MainWindow", "需要额外 %nan% 空间"))
        self.textBrowser_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">请等待我们从服务器下载必要的文件，大陆用户可能被GFW拦截，若无法下载请使用魔法。<span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.textBrowser_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">DLC Loading</span><span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.download_text.setText(_translate("MainWindow", "正在连接服务器...大陆用户如果长时间无法连接可能是GFW拦截，请使用魔法。"))
        self.next_button_5.setText(_translate("MainWindow", "下一步"))
        self.cancel_button_5.setText(_translate("MainWindow", "取消"))
        self.label.setText(_translate("MainWindow", "DLC 下载中:"))
        self.label_2.setText(_translate("MainWindow", "生成creamapi:"))
        self.speed_label.setText(_translate("MainWindow", "速度: %nan%"))
        self.label_3.setText(_translate("MainWindow", "DLC 下载进度:"))
        self.textBrowser_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">启动器重新安装</span><span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.textBrowser_13.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">您需要重新安装 Paradox 启动器才能正常运行。<span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.reinstall_button.setText(_translate("MainWindow", "完成"))
        self.cancel_button_6.setText(_translate("MainWindow", "取消"))
        self.reinstall_low.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">该程序将自动处理几乎所有事情，您只需按照屏幕上的说明进行操作即可。<span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.reinstall_up.setText(_translate("MainWindow", "你需要重新安装Paradox启动器以确保正确运行。"))
        self.progress_label.setText(_translate("MainWindow", "重新安装进度:"))
        self.now_reinstalling.setText(_translate("MainWindow", "等待中"))
        self.finish_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Overwriting the remaining files.<br /><br />请等待一下<span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.textBrowser_16.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">完成</span><span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.textBrowser_17.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">我们几乎已完成所有事情，只需再等待一小会儿。<span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.finish_button.setText(_translate("MainWindow", "完成"))
        self.launch_game.setText(_translate("MainWindow", "启动游戏"))
        self.checkBox.setText(_translate("MainWindow", "感谢安装，由@武乙凌薇翻译"))
        self.version.setText(_translate("MainWindow", "版本 %nan%"))
        self.textBrowser_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/GitHub-Logo.wine (1).png\" /><span style=\" font-size:10pt; color:#000000;\"> </span><a href=\"https://github.com/seuyh/stellaris-dlc-unlocker\"><span style=\" font-size:10pt; text-decoration: underline; color:#000000;\">GitHub</span></a></p></body></html>"))

