# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 235)
        Dialog.setMinimumSize(QtCore.QSize(450, 235))
        Dialog.setMaximumSize(QtCore.QSize(450, 235))
        Dialog.setStyleSheet("QDialog {\n"
"    background:rgb(51,51,51);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setStyleSheet("background:rgb(51,51,51);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame_2)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_top.setStyleSheet("background:rgb(91,90,90);")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_heading = QtWidgets.QLabel(self.frame_top)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.lab_heading.setFont(font)
        self.lab_heading.setStyleSheet("color:rgb(255,255,255);")
        self.lab_heading.setText("")
        self.lab_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_heading.setObjectName("lab_heading")
        self.horizontalLayout.addWidget(self.lab_heading)
        self.bn_close = QtWidgets.QPushButton(self.frame_top)
        self.bn_close.setMinimumSize(QtCore.QSize(55, 55))
        self.bn_close.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255,107,107);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI\\icons/1x/closeAsset 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_close.setIcon(icon)
        self.bn_close.setIconSize(QtCore.QSize(22, 22))
        self.bn_close.setAutoDefault(False)
        self.bn_close.setFlat(True)
        self.bn_close.setObjectName("bn_close")
        self.horizontalLayout.addWidget(self.bn_close)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_bottom = QtWidgets.QFrame(self.frame_2)
        self.frame_bottom.setStyleSheet("background:rgb(91,90,90);")
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_bottom)
        self.gridLayout.setContentsMargins(15, -1, 35, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.bn_east = QtWidgets.QPushButton(self.frame_bottom)
        self.bn_east.setMinimumSize(QtCore.QSize(80, 25))
        self.bn_east.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_east.setFont(font)
        self.bn_east.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_east.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}")
        self.bn_east.setText("")
        self.bn_east.setAutoDefault(False)
        self.bn_east.setObjectName("bn_east")
        self.gridLayout.addWidget(self.bn_east, 1, 3, 1, 1)
        self.lab_icon = QtWidgets.QLabel(self.frame_bottom)
        self.lab_icon.setMinimumSize(QtCore.QSize(40, 40))
        self.lab_icon.setMaximumSize(QtCore.QSize(40, 40))
        self.lab_icon.setText("")
        self.lab_icon.setObjectName("lab_icon")
        self.gridLayout.addWidget(self.lab_icon, 0, 0, 1, 1)
        self.bn_west = QtWidgets.QPushButton(self.frame_bottom)
        self.bn_west.setMinimumSize(QtCore.QSize(69, 25))
        self.bn_west.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.bn_west.setFont(font)
        self.bn_west.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_west.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(255,107,107);\n"
"    background-color: rgb(255,107,107);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(255,107,107);\n"
"    background-color: rgb(51,51,51);\n"
"}")
        self.bn_west.setText("")
        self.bn_west.setAutoDefault(False)
        self.bn_west.setObjectName("bn_west")
        self.gridLayout.addWidget(self.bn_west, 1, 2, 1, 1)
        self.lab_message = QtWidgets.QLabel(self.frame_bottom)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lab_message.setFont(font)
        self.lab_message.setStyleSheet("color:rgb(255,255,255);")
        self.lab_message.setText("")
        self.lab_message.setWordWrap(True)
        self.lab_message.setObjectName("lab_message")
        self.gridLayout.addWidget(self.lab_message, 0, 1, 1, 3)
        self.verticalLayout_2.addWidget(self.frame_bottom)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
