# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import UI.recources_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        MainWindow.setMinimumSize(QtCore.QSize(800, 550))
        MainWindow.setWindowTitle("Stellaris DLC Unlocker")
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setToolTip("")
        self.centralwidget.setStatusTip("")
        self.centralwidget.setWhatsThis("")
        self.centralwidget.setAccessibleName("")
        self.centralwidget.setStyleSheet("background:rgb(91,90,90);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_top_east = QtWidgets.QFrame(self.frame_top)
        self.frame_top_east.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_top_east.setStyleSheet("background:rgb(51,51,51);")
        self.frame_top_east.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_east.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top_east.setObjectName("frame_top_east")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_east)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_appname = QtWidgets.QFrame(self.frame_top_east)
        self.frame_appname.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_appname.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_appname.setObjectName("frame_appname")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_appname)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.bn_home = QtWidgets.QPushButton(self.frame_appname)
        self.bn_home.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_home.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_home.setToolTip("")
        self.bn_home.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/1x/homeAsset 46.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_home.setIcon(icon)
        self.bn_home.setIconSize(QtCore.QSize(22, 22))
        self.bn_home.setShortcut("")
        self.bn_home.setFlat(True)
        self.bn_home.setObjectName("bn_home")
        self.horizontalLayout_10.addWidget(self.bn_home)
        self.lappname_title = QtWidgets.QLabel(self.frame_appname)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(24)
        self.lappname_title.setFont(font)
        self.lappname_title.setToolTip("")
        self.lappname_title.setStyleSheet("color:rgb(255,255,255);")
        self.lappname_title.setText("<html><head/><body><p>Stellaris DLC Unlocker</p></body></html>")
        self.lappname_title.setObjectName("lappname_title")
        self.horizontalLayout_10.addWidget(self.lappname_title)
        self.horizontalLayout_4.addWidget(self.frame_appname)
        self.frame_user = QtWidgets.QFrame(self.frame_top_east)
        self.frame_user.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_user.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_user.setObjectName("frame_user")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_user)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.server_status = QtWidgets.QRadioButton(self.frame_user)
        self.server_status.setEnabled(True)
        self.server_status.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.server_status.setStyleSheet("QRadioButton::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    background-color: rgb(255,107,107);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    background-color: rgb(0,143,150);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: white;\n"
"}")
        self.server_status.setAutoExclusive(False)
        self.server_status.setObjectName("server_status")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.server_status)
        self.gh_status = QtWidgets.QRadioButton(self.frame_user)
        self.gh_status.setEnabled(True)
        self.gh_status.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gh_status.setStyleSheet("QRadioButton::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    background-color: rgb(255,107,107);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    background-color: rgb(0,143,150);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: white;\n"
"}")
        self.gh_status.setCheckable(True)
        self.gh_status.setChecked(False)
        self.gh_status.setAutoExclusive(False)
        self.gh_status.setObjectName("gh_status")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gh_status)
        self.horizontalLayout_9.addLayout(self.formLayout)
        self.horizontalLayout_4.addWidget(self.frame_user)
        self.frame_max = QtWidgets.QFrame(self.frame_top_east)
        self.frame_max.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_max.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_max.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_max.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_max.setObjectName("frame_max")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_max)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_min = QtWidgets.QFrame(self.frame_max)
        self.frame_min.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_min.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_min.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_min.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_min.setObjectName("frame_min")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_min)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6.addWidget(self.frame_min)
        self.horizontalLayout_4.addWidget(self.frame_max)
        self.frame_close = QtWidgets.QFrame(self.frame_top_east)
        self.frame_close.setMinimumSize(QtCore.QSize(55, 55))
        self.frame_close.setMaximumSize(QtCore.QSize(55, 55))
        self.frame_close.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_close.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_close.setObjectName("frame_close")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_close)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bn_close = QtWidgets.QPushButton(self.frame_close)
        self.bn_close.setMaximumSize(QtCore.QSize(55, 55))
        self.bn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_close.setToolTip("")
        self.bn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255,107,107);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/1x/closeAsset 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_close.setIcon(icon1)
        self.bn_close.setIconSize(QtCore.QSize(22, 22))
        self.bn_close.setShortcut("")
        self.bn_close.setFlat(True)
        self.bn_close.setObjectName("bn_close")
        self.horizontalLayout_5.addWidget(self.bn_close)
        self.horizontalLayout_4.addWidget(self.frame_close)
        self.horizontalLayout.addWidget(self.frame_top_east)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frame_bottom.setToolTip("")
        self.frame_bottom.setStatusTip("")
        self.frame_bottom.setWhatsThis("")
        self.frame_bottom.setAccessibleName("")
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_bottom_west = QtWidgets.QFrame(self.frame_bottom)
        self.frame_bottom_west.setMinimumSize(QtCore.QSize(80, 0))
        self.frame_bottom_west.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_bottom_west.setAccessibleName("")
        self.frame_bottom_west.setStyleSheet("background:rgb(51,51,51);")
        self.frame_bottom_west.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_west.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom_west.setObjectName("frame_bottom_west")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_bottom_west)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_home = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_home.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_home.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_home.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_home.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_home.setObjectName("frame_home")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_home)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_bug = QtWidgets.QFrame(self.frame_home)
        self.frame_bug.setMinimumSize(QtCore.QSize(80, 55))
        self.frame_bug.setMaximumSize(QtCore.QSize(160, 55))
        self.frame_bug.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bug.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bug.setObjectName("frame_bug")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_bug)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.bn_bug = QtWidgets.QPushButton(self.frame_bug)
        self.bn_bug.setMinimumSize(QtCore.QSize(80, 55))
        self.bn_bug.setMaximumSize(QtCore.QSize(160, 55))
        self.bn_bug.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bn_bug.setToolTip("")
        self.bn_bug.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(91,90,90);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.bn_bug.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/1x/bugAsset 47.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bn_bug.setIcon(icon2)
        self.bn_bug.setIconSize(QtCore.QSize(22, 22))
        self.bn_bug.setFlat(True)
        self.bn_bug.setObjectName("bn_bug")
        self.horizontalLayout_16.addWidget(self.bn_bug)
        self.horizontalLayout_15.addWidget(self.frame_bug)
        self.verticalLayout_3.addWidget(self.frame_home)
        self.frame_8 = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.version_label = QtWidgets.QLabel(self.frame_8)
        self.version_label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setKerning(True)
        self.version_label.setFont(font)
        self.version_label.setAccessibleName("")
        self.version_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.version_label.setStyleSheet("color:rgb(255,255,255);")
        self.version_label.setText("%version%")
        self.version_label.setAlignment(QtCore.Qt.AlignCenter)
        self.version_label.setObjectName("version_label")
        self.verticalLayout_4.addWidget(self.version_label)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout_2.addWidget(self.frame_bottom_west)
        self.frame_bottom_east = QtWidgets.QFrame(self.frame_bottom)
        self.frame_bottom_east.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_east.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom_east.setObjectName("frame_bottom_east")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_bottom_east)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_bottom_east)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 55))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setToolTip("")
        self.main_page.setStatusTip("")
        self.main_page.setWhatsThis("")
        self.main_page.setAccessibleName("")
        self.main_page.setStyleSheet("background:rgb(91,90,90);")
        self.main_page.setObjectName("main_page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.main_page)
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.first_main_page_label = QtWidgets.QLabel(self.main_page)
        self.first_main_page_label.setMinimumSize(QtCore.QSize(0, 55))
        self.first_main_page_label.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(24)
        self.first_main_page_label.setFont(font)
        self.first_main_page_label.setStyleSheet("QLabel {\n"
"    color:rgb(255,255,255);\n"
"}")
        self.first_main_page_label.setObjectName("first_main_page_label")
        self.horizontalLayout_13.addWidget(self.first_main_page_label)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.en_lang = QtWidgets.QRadioButton(self.main_page)
        self.en_lang.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.en_lang.setStyleSheet("padding-left: 5px")
        self.en_lang.setText("")
        self.en_lang.setChecked(True)
        self.en_lang.setObjectName("en_lang")
        self.gridLayout_3.addWidget(self.en_lang, 1, 1, 1, 1)
        self.ru_lang = QtWidgets.QRadioButton(self.main_page)
        self.ru_lang.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ru_lang.setStyleSheet("padding-left: 5px")
        self.ru_lang.setText("")
        self.ru_lang.setObjectName("ru_lang")
        self.gridLayout_3.addWidget(self.ru_lang, 1, 2, 1, 1)
        self.cn_lang = QtWidgets.QRadioButton(self.main_page)
        self.cn_lang.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cn_lang.setStyleSheet("padding-left: 5px")
        self.cn_lang.setText("")
        self.cn_lang.setObjectName("cn_lang")
        self.gridLayout_3.addWidget(self.cn_lang, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.main_page)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("QLabel {\n"
"    color:rgb(255,255,255);\n"
"}")
        self.label.setText("EN")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.main_page)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color:rgb(255,255,255);\n"
"}")
        self.label_3.setText("РУ")
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.main_page)
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color:rgb(255,255,255);\n"
"}")
        self.label_4.setText("简中")
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.horizontalLayout_13.addLayout(self.gridLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.frame_2 = QtWidgets.QFrame(self.main_page)
        self.frame_2.setEnabled(True)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 370))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_page_browser = QtWidgets.QTextBrowser(self.frame_2)
        self.main_page_browser.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.main_page_browser.setFont(font)
        self.main_page_browser.setAcceptDrops(False)
        self.main_page_browser.setToolTip("")
        self.main_page_browser.setStatusTip("")
        self.main_page_browser.setWhatsThis("")
        self.main_page_browser.setAccessibleName("")
        self.main_page_browser.setStyleSheet("\n"
"QScrollBar::groove:vertical {\n"
"        background: red;\n"
"        width:5px\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"        height: 10px;\n"
"        background:rgb(0,143,170);\n"
"    margin:0 -8px\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"        background:rgb(51,51,51);\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"        background:rgb(51,51,51);\n"
"}\n"
"\n"
"QListWidget {\n"
"    color: white;\n"
"    font-size: 15px;\n"
"};\n"
"color: white;\n"
"border: none;\n"
"background-color: rgb(51,51,51);\n"
"")
        self.main_page_browser.setInputMethodHints(QtCore.Qt.ImhNone)
        self.main_page_browser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.main_page_browser.setPlaceholderText("")
        self.main_page_browser.setObjectName("main_page_browser")
        self.gridLayout_2.addWidget(self.main_page_browser, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 162, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.frame_3 = QtWidgets.QFrame(self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem5 = QtWidgets.QSpacerItem(602, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.next_button = QtWidgets.QPushButton(self.frame_3)
        self.next_button.setMinimumSize(QtCore.QSize(79, 25))
        self.next_button.setMaximumSize(QtCore.QSize(69, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.next_button.setFont(font)
        self.next_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_18.addWidget(self.next_button)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.main_page)
        self.work_page = QtWidgets.QWidget()
        self.work_page.setStyleSheet("background:rgb(91,90,90);")
        self.work_page.setObjectName("work_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.work_page)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.work_page_label = QtWidgets.QLabel(self.work_page)
        self.work_page_label.setMinimumSize(QtCore.QSize(0, 55))
        self.work_page_label.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(24)
        self.work_page_label.setFont(font)
        self.work_page_label.setToolTip("")
        self.work_page_label.setStyleSheet("color:rgb(255,255,255);")
        self.work_page_label.setObjectName("work_page_label")
        self.verticalLayout_7.addWidget(self.work_page_label)
        self.frame_bug_main = QtWidgets.QFrame(self.work_page)
        self.frame_bug_main.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_bug_main.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_bug_main.setToolTip("")
        self.frame_bug_main.setAutoFillBackground(False)
        self.frame_bug_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bug_main.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bug_main.setObjectName("frame_bug_main")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_bug_main)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.alternative_unloc_checkbox = QtWidgets.QCheckBox(self.frame_bug_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.alternative_unloc_checkbox.setFont(font)
        self.alternative_unloc_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.alternative_unloc_checkbox.setToolTip("")
        self.alternative_unloc_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.alternative_unloc_checkbox.setStyleSheet("QCheckBox {\n"
"        color:rgb(255,255,255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"        width: 12px;\n"
"        height: 12px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"        border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"       background:rgb(0,143,170);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(0,143,150);\n"
"        border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"        border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"")
        self.alternative_unloc_checkbox.setObjectName("alternative_unloc_checkbox")
        self.horizontalLayout_19.addWidget(self.alternative_unloc_checkbox)
        self.label_2 = QtWidgets.QLabel(self.frame_bug_main)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.label_2.setStyleSheet("padding-bottom: 10px;")
        self.label_2.setText("?")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_19.addWidget(self.label_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_19, 2, 1, 1, 1)
        self.lab_bullet3 = QtWidgets.QLabel(self.frame_bug_main)
        self.lab_bullet3.setMaximumSize(QtCore.QSize(5, 16777215))
        self.lab_bullet3.setText("")
        self.lab_bullet3.setPixmap(QtGui.QPixmap("UI\\Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/bulletAsset 54.png"))
        self.lab_bullet3.setObjectName("lab_bullet3")
        self.gridLayout.addWidget(self.lab_bullet3, 3, 0, 1, 1)
        self.lab_bullet = QtWidgets.QLabel(self.frame_bug_main)
        self.lab_bullet.setMaximumSize(QtCore.QSize(5, 16777215))
        self.lab_bullet.setText("")
        self.lab_bullet.setPixmap(QtGui.QPixmap("UI\\Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/bulletAsset 54.png"))
        self.lab_bullet.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_bullet.setObjectName("lab_bullet")
        self.gridLayout.addWidget(self.lab_bullet, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 7, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(421, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 5, 6, 1, 1)
        self.dlc_status_widget = QtWidgets.QListWidget(self.frame_bug_main)
        self.dlc_status_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dlc_status_widget.sizePolicy().hasHeightForWidth())
        self.dlc_status_widget.setSizePolicy(sizePolicy)
        self.dlc_status_widget.setMinimumSize(QtCore.QSize(230, 150))
        self.dlc_status_widget.setMaximumSize(QtCore.QSize(460, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.dlc_status_widget.setFont(font)
        self.dlc_status_widget.setToolTip("")
        self.dlc_status_widget.setStatusTip("")
        self.dlc_status_widget.setWhatsThis("")
        self.dlc_status_widget.setAccessibleName("")
        self.dlc_status_widget.setStyleSheet("\n"
"QScrollBar::groove:vertical {\n"
"        background: red;\n"
"        width:5px\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"        height: 10px;\n"
"        background:rgb(0,143,170);\n"
"    margin:0 -8px\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"        background:rgb(51,51,51);\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"        background:rgb(51,51,51);\n"
"}\n"
"\n"
"QListWidget {\n"
"    color: white;\n"
"    font-size: 15px;\n"
"};\n"
"border: none;\n"
"background-color: rgb(51,51,51);\n"
"\n"
"")
        self.dlc_status_widget.setAutoScroll(False)
        self.dlc_status_widget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dlc_status_widget.setProperty("showDropIndicator", False)
        self.dlc_status_widget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.dlc_status_widget.setObjectName("dlc_status_widget")
        item = QtWidgets.QListWidgetItem()
        item.setText("DLC Status")
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.dlc_status_widget.addItem(item)
        self.gridLayout.addWidget(self.dlc_status_widget, 0, 6, 1, 1)
        self.lab_bullet2 = QtWidgets.QLabel(self.frame_bug_main)
        self.lab_bullet2.setMaximumSize(QtCore.QSize(5, 16777215))
        self.lab_bullet2.setText("")
        self.lab_bullet2.setPixmap(QtGui.QPixmap("UI\\Minimalistic-Flat-Modern-GUI-Template-master/icons/1x/bulletAsset 54.png"))
        self.lab_bullet2.setObjectName("lab_bullet2")
        self.gridLayout.addWidget(self.lab_bullet2, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.game_path_label = QtWidgets.QLabel(self.frame_bug_main)
        self.game_path_label.setMinimumSize(QtCore.QSize(0, 0))
        self.game_path_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.game_path_label.setFont(font)
        self.game_path_label.setToolTip("")
        self.game_path_label.setStatusTip("")
        self.game_path_label.setWhatsThis("")
        self.game_path_label.setStyleSheet("color:rgb(255,255,255);")
        self.game_path_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.game_path_label.setObjectName("game_path_label")
        self.horizontalLayout_8.addWidget(self.game_path_label)
        self.game_path_line = QtWidgets.QLineEdit(self.frame_bug_main)
        self.game_path_line.setMinimumSize(QtCore.QSize(200, 25))
        self.game_path_line.setAccessibleName("")
        self.game_path_line.setStyleSheet("QLineEdit {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(51,51,51);\n"
"    border-radius:4px;\n"
"    background:rgb(51,51,51);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    color:rgb(255,255,255);\n"
"    border:2px solid rgb(112,112,112);\n"
"    border-radius:4px;\n"
"    background:rgb(112,112,112);\n"
"}")
        self.game_path_line.setText("")
        self.game_path_line.setPlaceholderText("")
        self.game_path_line.setObjectName("game_path_line")
        self.horizontalLayout_8.addWidget(self.game_path_line)
        self.path_choose_button = QtWidgets.QPushButton(self.frame_bug_main)
        self.path_choose_button.setMinimumSize(QtCore.QSize(60, 25))
        self.path_choose_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.path_choose_button.setToolTip("")
        self.path_choose_button.setStatusTip("")
        self.path_choose_button.setWhatsThis("")
        self.path_choose_button.setAccessibleName("")
        self.path_choose_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.path_choose_button.setObjectName("path_choose_button")
        self.horizontalLayout_8.addWidget(self.path_choose_button)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem9)
        self.unlock_button = QtWidgets.QPushButton(self.frame_bug_main)
        self.unlock_button.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.unlock_button.setFont(font)
        self.unlock_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.unlock_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.unlock_button.setObjectName("unlock_button")
        self.horizontalLayout_23.addWidget(self.unlock_button)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem10)
        self.gridLayout.addLayout(self.horizontalLayout_23, 5, 1, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(0, -1, 100, -1)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.full_reinstall_checkbox = QtWidgets.QCheckBox(self.frame_bug_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.full_reinstall_checkbox.setFont(font)
        self.full_reinstall_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.full_reinstall_checkbox.setToolTip("")
        self.full_reinstall_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.full_reinstall_checkbox.setAutoFillBackground(False)
        self.full_reinstall_checkbox.setStyleSheet("QCheckBox {\n"
"        color:rgb(255,255,255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"        width: 12px;\n"
"        height: 12px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"        border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"       background:rgb(0,143,170);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(0,143,150);\n"
"        border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"        border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"")
        self.full_reinstall_checkbox.setTristate(False)
        self.full_reinstall_checkbox.setObjectName("full_reinstall_checkbox")
        self.horizontalLayout_17.addWidget(self.full_reinstall_checkbox)
        self.full_reinstall_tooltip = QtWidgets.QLabel(self.frame_bug_main)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.full_reinstall_tooltip.setFont(font)
        self.full_reinstall_tooltip.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.full_reinstall_tooltip.setMouseTracking(False)
        self.full_reinstall_tooltip.setAcceptDrops(False)
        self.full_reinstall_tooltip.setToolTipDuration(-1)
        self.full_reinstall_tooltip.setStatusTip("")
        self.full_reinstall_tooltip.setWhatsThis("")
        self.full_reinstall_tooltip.setAccessibleName("")
        self.full_reinstall_tooltip.setStyleSheet("padding-bottom: 10px;")
        self.full_reinstall_tooltip.setText("?")
        self.full_reinstall_tooltip.setObjectName("full_reinstall_tooltip")
        self.horizontalLayout_17.addWidget(self.full_reinstall_tooltip)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout_17, 1, 1, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.skip_launcher_reinstall_checbox = QtWidgets.QCheckBox(self.frame_bug_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.skip_launcher_reinstall_checbox.setFont(font)
        self.skip_launcher_reinstall_checbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.skip_launcher_reinstall_checbox.setToolTip("")
        self.skip_launcher_reinstall_checbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.skip_launcher_reinstall_checbox.setStyleSheet("QCheckBox {\n"
"        color:rgb(255,255,255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"        width: 12px;\n"
"        height: 12px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"        border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"       background:rgb(0,143,170);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(0,143,150);\n"
"        border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"        border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"")
        self.skip_launcher_reinstall_checbox.setObjectName("skip_launcher_reinstall_checbox")
        self.horizontalLayout_22.addWidget(self.skip_launcher_reinstall_checbox)
        self.skip_launcher_reinstall_tooltip = QtWidgets.QLabel(self.frame_bug_main)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.skip_launcher_reinstall_tooltip.setFont(font)
        self.skip_launcher_reinstall_tooltip.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.skip_launcher_reinstall_tooltip.setStyleSheet("padding-bottom: 10px;")
        self.skip_launcher_reinstall_tooltip.setText("?")
        self.skip_launcher_reinstall_tooltip.setObjectName("skip_launcher_reinstall_tooltip")
        self.horizontalLayout_22.addWidget(self.skip_launcher_reinstall_tooltip)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem12)
        self.gridLayout.addLayout(self.horizontalLayout_22, 3, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_bug_main)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem13)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(50, -1, 50, -1)
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.progress_label = QtWidgets.QLabel(self.work_page)
        self.progress_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.progress_label.setFont(font)
        self.progress_label.setStyleSheet("color:rgb(255,255,255);")
        self.progress_label.setObjectName("progress_label")
        self.verticalLayout_11.addWidget(self.progress_label)
        self.download_files_radio = QtWidgets.QRadioButton(self.work_page)
        self.download_files_radio.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.download_files_radio.setFont(font)
        self.download_files_radio.setStyleSheet("QRadioButton::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    background-color: rgb(255,107,107);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    background-color: rgb(0,143,150);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: white;\n"
"}")
        self.download_files_radio.setCheckable(True)
        self.download_files_radio.setAutoRepeat(False)
        self.download_files_radio.setAutoExclusive(False)
        self.download_files_radio.setObjectName("download_files_radio")
        self.verticalLayout_11.addWidget(self.download_files_radio)
        self.launcher_reinstall_radio = QtWidgets.QRadioButton(self.work_page)
        self.launcher_reinstall_radio.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.launcher_reinstall_radio.setFont(font)
        self.launcher_reinstall_radio.setStyleSheet("QRadioButton::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    background-color: rgb(255,107,107);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    background-color: rgb(0,143,150);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: white;\n"
"}")
        self.launcher_reinstall_radio.setAutoExclusive(False)
        self.launcher_reinstall_radio.setObjectName("launcher_reinstall_radio")
        self.verticalLayout_11.addWidget(self.launcher_reinstall_radio)
        self.copy_files_radio = QtWidgets.QRadioButton(self.work_page)
        self.copy_files_radio.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.copy_files_radio.setFont(font)
        self.copy_files_radio.setStyleSheet("QRadioButton::indicator {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    background-color: rgb(255,107,107);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    background-color: rgb(0,143,150);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: white;\n"
"}")
        self.copy_files_radio.setAutoExclusive(False)
        self.copy_files_radio.setObjectName("copy_files_radio")
        self.verticalLayout_11.addWidget(self.copy_files_radio)
        self.horizontalLayout_20.addLayout(self.verticalLayout_11)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem14)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dlc_download_label = QtWidgets.QLabel(self.work_page)
        self.dlc_download_label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.dlc_download_label.setFont(font)
        self.dlc_download_label.setMouseTracking(False)
        self.dlc_download_label.setStyleSheet("color: white")
        self.dlc_download_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dlc_download_label.setObjectName("dlc_download_label")
        self.verticalLayout_6.addWidget(self.dlc_download_label)
        self.dlc_download_progress_bar = QtWidgets.QProgressBar(self.work_page)
        self.dlc_download_progress_bar.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.dlc_download_progress_bar.setFont(font)
        self.dlc_download_progress_bar.setAccessibleName("")
        self.dlc_download_progress_bar.setStyleSheet("QProgressBar\n"
"{\n"
"    color:rgb(255,255,255);\n"
"    background-color :rgb(51,51,51);\n"
"    border : 2px;\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border : 2px;\n"
"    border-radius:4px;\n"
"    background-color:rgb(0,143,170);\n"
"}")
        self.dlc_download_progress_bar.setProperty("value", 0)
        self.dlc_download_progress_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.dlc_download_progress_bar.setTextVisible(True)
        self.dlc_download_progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.dlc_download_progress_bar.setInvertedAppearance(False)
        self.dlc_download_progress_bar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.dlc_download_progress_bar.setFormat("%p%")
        self.dlc_download_progress_bar.setObjectName("dlc_download_progress_bar")
        self.verticalLayout_6.addWidget(self.dlc_download_progress_bar)
        self.current_dlc_label = QtWidgets.QLabel(self.work_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.current_dlc_label.setFont(font)
        self.current_dlc_label.setStyleSheet("color: white")
        self.current_dlc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.current_dlc_label.setObjectName("current_dlc_label")
        self.verticalLayout_6.addWidget(self.current_dlc_label)
        self.current_dlc_progress_bar = QtWidgets.QProgressBar(self.work_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.current_dlc_progress_bar.setFont(font)
        self.current_dlc_progress_bar.setStyleSheet("QProgressBar\n"
"{\n"
"    color:rgb(255,255,255);\n"
"    background-color :rgb(51,51,51);\n"
"    border : 2px;\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border : 2px;\n"
"    border-radius:4px;\n"
"    background-color:rgb(0,143,170);\n"
"}")
        self.current_dlc_progress_bar.setProperty("value", 0)
        self.current_dlc_progress_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.current_dlc_progress_bar.setFormat("%p%")
        self.current_dlc_progress_bar.setObjectName("current_dlc_progress_bar")
        self.verticalLayout_6.addWidget(self.current_dlc_progress_bar)
        self.speed_label = QtWidgets.QLabel(self.work_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.speed_label.setFont(font)
        self.speed_label.setStyleSheet("color: white")
        self.speed_label.setText("")
        self.speed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_label.setObjectName("speed_label")
        self.verticalLayout_6.addWidget(self.speed_label)
        self.horizontalLayout_20.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        spacerItem15 = QtWidgets.QSpacerItem(20, 197, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem15)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem16)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lauch_game_checkbox = QtWidgets.QCheckBox(self.work_page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lauch_game_checkbox.setFont(font)
        self.lauch_game_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lauch_game_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lauch_game_checkbox.setStyleSheet("QCheckBox {\n"
"        color:rgb(255,255,255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"        width: 12px;\n"
"        height: 12px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"        border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"    border:2px solid rgb(51,51,51);\n"
"       background:rgb(0,143,170);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(0,143,150);\n"
"        border: 2px solid rgb(51,51,51);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:pressed {\n"
"        border:2px solid rgb(51,51,51);\n"
"    background:rgb(91,90,90);\n"
"}\n"
"")
        self.lauch_game_checkbox.setChecked(True)
        self.lauch_game_checkbox.setObjectName("lauch_game_checkbox")
        self.verticalLayout_10.addWidget(self.lauch_game_checkbox)
        spacerItem17 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_10.addItem(spacerItem17)
        self.done_button = QtWidgets.QPushButton(self.work_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.done_button.setFont(font)
        self.done_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.done_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(255,255,255);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(0,143,150);\n"
"}\n"
"QPushButton:pressed {    \n"
"    border: 2px solid rgb(0,143,150);\n"
"    background-color: rgb(51,51,51);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    border-radius: 5px;    \n"
"    border: 2px solid rgb(112,112,112);\n"
"    background-color: rgb(112,112,112);\n"
"}")
        self.done_button.setShortcut("")
        self.done_button.setObjectName("done_button")
        self.verticalLayout_10.addWidget(self.done_button)
        self.horizontalLayout_21.addLayout(self.verticalLayout_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.stackedWidget.addWidget(self.work_page)
        self.bug_page = QtWidgets.QWidget()
        self.bug_page.setObjectName("bug_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.bug_page)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bug_page_title = QtWidgets.QLabel(self.bug_page)
        self.bug_page_title.setMinimumSize(QtCore.QSize(0, 55))
        self.bug_page_title.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(24)
        self.bug_page_title.setFont(font)
        self.bug_page_title.setStyleSheet("QLabel {\n"
"    color:rgb(255,255,255);\n"
"}")
        self.bug_page_title.setObjectName("bug_page_title")
        self.verticalLayout_5.addWidget(self.bug_page_title)
        self.log_widget = QtWidgets.QListWidget(self.bug_page)
        self.log_widget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.log_widget.setFont(font)
        self.log_widget.setToolTip("")
        self.log_widget.setStatusTip("")
        self.log_widget.setWhatsThis("")
        self.log_widget.setAccessibleName("")
        self.log_widget.setStyleSheet("\n"
"QScrollBar::groove:vertical {\n"
"        background: red;\n"
"        width:5px\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"        height: 10px;\n"
"        background:rgb(0,143,170);\n"
"    margin:0 -8px\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"        background:rgb(51,51,51);\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"        background:rgb(51,51,51);\n"
"}\n"
"\n"
"QListWidget {\n"
"    color: white;\n"
"    font-size: 15px;\n"
"};\n"
"border: none;\n"
"background-color: rgb(51,51,51);\n"
"\n"
"")
        self.log_widget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.log_widget.setProperty("showDropIndicator", False)
        self.log_widget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.log_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.log_widget.setSelectionRectVisible(False)
        self.log_widget.setObjectName("log_widget")
        item = QtWidgets.QListWidgetItem()
        item.setText("Nothing to display")
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.log_widget.addItem(item)
        self.verticalLayout_5.addWidget(self.log_widget)
        self.stackedWidget.addWidget(self.bug_page)
        self.horizontalLayout_14.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_low = QtWidgets.QFrame(self.frame_bottom_east)
        self.frame_low.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_low.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_low.setAccessibleName("")
        self.frame_low.setStyleSheet("")
        self.frame_low.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_low.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_low.setObjectName("frame_low")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_low)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_tab = QtWidgets.QFrame(self.frame_low)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_tab.setFont(font)
        self.frame_tab.setStyleSheet("background:rgb(51,51,51);")
        self.frame_tab.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_tab.setObjectName("frame_tab")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_tab)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.bottom_label_github = QtWidgets.QLabel(self.frame_tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.bottom_label_github.setFont(font)
        self.bottom_label_github.setAccessibleName("")
        self.bottom_label_github.setStyleSheet("color:rgb(255,255,255);")
        self.bottom_label_github.setText("<html><head/><body><p><img src=\":/soicials/icons/social/GitHub-Logo.wine.png\"/>GitHub: <a href=\"https://github.com/seuyh/stellaris-dlc-unlocker\"><span style=\" text-decoration: underline; color:#008f96;\">github.com/seuyh/stellaris-dlc-unlocker</span></a></p></body></html>")
        self.bottom_label_github.setAlignment(QtCore.Qt.AlignCenter)
        self.bottom_label_github.setObjectName("bottom_label_github")
        self.horizontalLayout_12.addWidget(self.bottom_label_github)
        self.horizontalLayout_11.addWidget(self.frame_tab)
        self.verticalLayout_2.addWidget(self.frame_low)
        self.horizontalLayout_2.addWidget(self.frame_bottom_east)
        self.verticalLayout.addWidget(self.frame_bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.server_status.setText(_translate("MainWindow", "Server connection"))
        self.gh_status.setText(_translate("MainWindow", "Github conncection"))
        self.first_main_page_label.setText(_translate("MainWindow", "Welcome"))
        self.main_page_browser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; text-decoration: underline; color:#008f96;\">Stellaris DLC Unlocker</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; text-decoration: underline;\">Requirements</span><span style=\" font-family:\'MS Shell Dlg 2\';\">:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">  </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">License</span><span style=\" font-family:\'MS Shell Dlg 2\';\">: Steam.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; text-decoration: underline;\">Installation</span><span style=\" font-family:\'MS Shell Dlg 2\';\">:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">  Follow the installer instructions. Installation is almost entirely automatic. <br /></span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; text-decoration: underline; color:#008f96;\">Terms Of Use</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; color:#0000ff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">1. This unlocker is distributed absolutely free of charge. Any commercial use of this unlocker is prohibited. If you purchased from any source, please refund and give a negative review.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">2. THIS UNLOCKER IS PROVIDED &quot;AS IS&quot;. NO WARRANTIES ARE PROVIDED OR IMPLIED. YOU USE THIS MODIFICATION OF THE ORIGINAL GAME AT YOUR OWN RISK. THE AUTHORS OF THE MODIFICATION WILL NOT BE LIABLE FOR ANY LOSSES OR DATA CORRUPTION, ANY LOST PROFITS IN THE PROCESS OF USE OR MISUSE OF THIS MODIFICATION.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">3. All rights not expressly granted here are reserved by the copyright holders.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">4. Installation and use of this modification implies that you have read and understand the terms of this license agreement and agree to them.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.work_page_label.setText(_translate("MainWindow", "Unlock settings"))
        self.alternative_unloc_checkbox.setText(_translate("MainWindow", "Alternative unlock"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Uses a different unlock method</p></body></html>"))
        __sortingEnabled = self.dlc_status_widget.isSortingEnabled()
        self.dlc_status_widget.setSortingEnabled(False)
        self.dlc_status_widget.setSortingEnabled(__sortingEnabled)
        self.game_path_label.setText(_translate("MainWindow", "Stellaris path", "sadsadsa"))
        self.path_choose_button.setText(_translate("MainWindow", "Open"))
        self.unlock_button.setText(_translate("MainWindow", "Unlock"))
        self.full_reinstall_checkbox.setText(_translate("MainWindow", "Full launcher reinstallation"))
        self.full_reinstall_tooltip.setToolTip(_translate("MainWindow", "<html><head/><body><p>This function will delete all saves and presets of mods.</p><p>It is only needed if something did not work during the normal installation</p></body></html>"))
        self.skip_launcher_reinstall_checbox.setText(_translate("MainWindow", "Skip launcher reinstall"))
        self.skip_launcher_reinstall_tooltip.setToolTip(_translate("MainWindow", "<html><head/><body><p>It is used if it is impossible to automatically reinstall the launcher.</p><p>The program will assume that the launcher has already been reinstalled before</p></body></html>"))
        self.progress_label.setText(_translate("MainWindow", "Progress"))
        self.download_files_radio.setText(_translate("MainWindow", "Download files"))
        self.launcher_reinstall_radio.setText(_translate("MainWindow", "Launcher reinstall"))
        self.copy_files_radio.setText(_translate("MainWindow", "Copy files"))
        self.dlc_download_label.setText(_translate("MainWindow", "DLC Download progress"))
        self.current_dlc_label.setText(_translate("MainWindow", "Current DLC progress"))
        self.lauch_game_checkbox.setText(_translate("MainWindow", "Launch game"))
        self.done_button.setText(_translate("MainWindow", "Done"))
        self.bug_page_title.setText(_translate("MainWindow", "Log"))
        __sortingEnabled = self.log_widget.isSortingEnabled()
        self.log_widget.setSortingEnabled(False)
        self.log_widget.setSortingEnabled(__sortingEnabled)
